# Dockerfile > Docker Image > Run Docker Containers

FROM alpine:latest
LABEL org.opencontainers.image.source=https://github.com/agdebroise/mslearn-exercise-publish-package

CMD [ "echo", "hello from packages" ]
